# Generated by Django 3.0.5 on 2020-08-20 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmpages', '0002_auto_20200818_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorform',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
