# Generated by Django 3.0.5 on 2020-08-20 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmpages', '0003_auto_20200820_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='visitform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('purpose', models.CharField(max_length=20, null=True)),
                ('phone', models.CharField(max_length=10, null=True)),
                ('time', models.CharField(max_length=8, null=True)),
                ('date', models.CharField(max_length=10, null=True)),
                ('hours', models.CharField(max_length=8, null=True)),
            ],
        ),
    ]
