# Generated by Django 3.0.5 on 2020-08-20 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmpages', '0004_visitform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitform',
            old_name='hours',
            new_name='insti',
        ),
    ]
