# Generated by Django 3.0.5 on 2020-08-20 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmpages', '0005_auto_20200820_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitform',
            name='date',
            field=models.CharField(max_length=44, null=True),
        ),
        migrations.AlterField(
            model_name='visitform',
            name='insti',
            field=models.CharField(max_length=44, null=True),
        ),
        migrations.AlterField(
            model_name='visitform',
            name='time',
            field=models.CharField(max_length=44, null=True),
        ),
    ]
